name: Terraform Check

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init & Validate Day1
      working-directory: day1
      run: |
        terraform init
        terraform validate

    - name: Terraform Init & Validate Day2
      working-directory: day2
      run: |
        terraform init
        terraform validate

    - name: Terraform Init & Validate Day3
      working-directory: day3
      run: |
        terraform init
        terraform validate

    - name: Terraform Init & Validate Day4
      working-directory: day4
      run: |
        terraform init
        terraform validate