name: Terraform Check

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Validate Day1
      working-directory: day1
      run: |
        terraform init -backend=false
        terraform validate

    - name: Validate Day2
      working-directory: day2
      run: |
        terraform init -backend=false
        terraform validate